name: IaC Scan Demo Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  orca-iac-scan-job:
    name: IaC Security Scan
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Orca IaC Security Scan
      uses: orcasecurity/shiftleft-iac-action@v1
      with:
          api_token: ${{ secrets.ORCA_SECURITY_API_TOKEN }}
          project_key: "default"
          path: "iac"
resource "azurerm_resource_group" "positive1" {
  name     = "acceptanceTestResourceGroup1"
  location = "West US"
}

resource "azurerm_sql_server" "positive2" {
  name                         = "mysqlserver1"
  resource_group_name          = "acceptanceTestResourceGroup1"
  location                     = "West US"
  version                      = "12.0"
  administrator_login          = "4dm1n157r470r"
  administrator_login_password = "4-v3ry-53cr37-p455w0rd"
}

resource "azurerm_sql_active_directory_administrator" "positive3" {
  server_name         = "mysqlserver2"
  resource_group_name = "acceptanceTestResourceGroup1"
  login               = "sqladmin"
  tenant_id           = data.azurerm_client_config.current.tenant_id
  object_id           = data.azurerm_client_config.current.object_id
}
